# Generated by Django 5.2.4 on 2025-07-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=100)),
                ('Document', models.FileField(upload_to='documents/')),
                ('DateRegistered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Resident', models.CharField(choices=[('Ug', 'Ug'), ('Tz', 'Tz')], max_length=100)),
                ('NationalId', models.CharField(max_length=10)),
                ('License', models.FileField(upload_to='licenses/')),
                ('RegisteredDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department', models.CharField(choices=[('Hr', 'Hr'), ('Sales', 'Sales'), ('Marketing', 'Marketing')], max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateRegistered', models.DateTimeField(auto_now_add=True)),
                ('BankReceipt', models.FileField(upload_to='compensationReceipt/')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('FullName', models.CharField(max_length=100)),
                ('Role', models.CharField(choices=[('Manager', 'Manager'), ('Cashier', 'Cashier'), ('admin', 'Admin')], max_length=100)),
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.department')),
            ],
        ),
    ]
